name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - name: Run script file
        run: |
          chmod +x ./setup/setup.sh
          ./setup/setup.sh
        shell: bash
      - name: Run tests
        run: go test -v -cover ./...