name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.2.0
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

  goimports:
    name: Perform goimports
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Run goimports
        uses: Jerome1337/goimports-action@v1.0.3

  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    needs: [lint, goimports]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.2.0
      - name: Run tests
        run: go test -v -cover -v ./...
