name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.2.0
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2
      - name: Setup go
        uses: actions/setup-go@v3.2.0
      - name: Run tests
        run: go test -v -cover ./...